index:
    path: /
    controller: App\Controller\TodolistController::IndexAction


edit_route:
    path: /edit
    controller: App\Controller\TodolistController::EditAction

signin_route:
    path: /signin
    controller: App\Controller\AuthController::SigninAction

add_route:
    path: /add
    controller: App\Controller\TodolistController::AddAction